import type { NextPage } from 'next';
import Head from 'next/head';
import { css } from '@emotion/react';

import { Button } from '../stories/Button';

const Home: NextPage = () => {
  return (
    <div css={container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button size="large" label="버튼" />
      </main>
    </div>
  );
};

const container = css`
  width: 100%;
  max-width: 1280px;
  margin: 0 auto;
`;

export default Home;
